import { useState } from 'react';
import { Bot } from 'lucide-react';
import { Button, Card, Textarea } from '../components/ui';
import { useLearningStore } from '../store/useLearningStore';
import { AiMode } from '../types';

const modes: {id:AiMode; label:string}[]=[{id:'tutor',label:'Tutor'},{id:'exam',label:'Exam'},{id:'grammar',label:'Grammar'},{id:'speaking',label:'Speaking'},{id:'review',label:'Review'}];
export default function AiAssistant(){
 const {messages, sendAiMessage, grades, knowledge, lessons}=useLearningStore(); const [text,setText]=useState(''); const [mode,setMode]=useState<AiMode>('tutor');
 const submit=()=>{ if(!text.trim()) return; sendAiMessage(text,mode); setText(''); };
 return <div className="space-y-5"><div><h1 className="text-3xl font-black">AI-репетитор</h1><p className="text-slate-400">Это не быстрые команды, а рабочее пространство. Сейчас AI — локальная симуляция без API, но ответы строятся по твоим данным.</p></div><div className="grid gap-4 lg:grid-cols-[1fr_340px]"><Card className="min-h-[650px]"><div className="mb-4 flex flex-wrap gap-2">{modes.map(m=><button key={m.id} onClick={()=>setMode(m.id)} className={`rounded-2xl px-4 py-2 ${mode===m.id?'bg-cyan-300 text-slate-950':'bg-white/5 text-slate-300'}`}>{m.label}</button>)}</div><div className="space-y-4">{messages.map(m=><div key={m.id} className={`max-w-[85%] rounded-3xl p-4 ${m.role==='user'?'ml-auto bg-cyan-300 text-slate-950':'bg-white/5 text-slate-200'}`}><p className="whitespace-pre-wrap">{m.text}</p></div>)}</div><div className="mt-5 grid gap-3 sm:grid-cols-[1fr_auto]"><Textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Напиши задачу AI: проверь ответ, дай задание, объясни грамматику..." className="min-h-24"/><Button onClick={submit} className="px-8"><Bot className="mr-2 inline"/>Отправить</Button></div></Card><Card><h2 className="text-xl font-bold">Контекст, который видит AI</h2><div className="mt-4 space-y-4 text-sm text-slate-300"><div className="rounded-2xl bg-white/5 p-4"><b>Оценки:</b><p>{grades.length} записей, средний балл считается в табеле.</p></div><div className="rounded-2xl bg-white/5 p-4"><b>База знаний:</b><p>{knowledge.length} записей, {knowledge.filter(k=>k.nextReview<=new Date().toISOString().slice(0,10)).length} требуют повторения.</p></div><div className="rounded-2xl bg-white/5 p-4"><b>Задания:</b><p>{lessons.filter(l=>l.status!=='completed').length} активных/запланированных.</p></div><p className="text-xs text-slate-500">Для настоящих ответов как ChatGPT позже подключается OpenAI API через безопасный serverless backend. На GitHub Pages API-ключ хранить нельзя.</p></div></Card></div></div>;
}
