import { Bar, BarChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Card } from '../components/ui';
import { useLearningStore } from '../store/useLearningStore';
import { averageGrade, forecastB1, knowledgeCoverage, skillAverage, strongTopics, weakTopics } from '../utils/analytics';

export default function Analytics(){
 const {grades, knowledge, activity}=useLearningStore(); const skills=['Разговор','Грамматика','Словарь','Аудирование','Произношение','Письмо'];
 const skillData=skills.map(s=>({skill:s, score:skillAverage(grades,s), confidence:grades.filter(g=>g.type===s).length})).filter(s=>s.score);
 const lineData=[...grades].reverse().map((g,i)=>({n:`#${i+1}`, score:g.score, topic:g.topic})); const months=forecastB1(activity,grades);
 return <div className="space-y-5"><div><h1 className="text-3xl font-black">Аналитика</h1><p className="text-slate-400">Каждая метрика объясняет источник данных. Если данных мало — система показывает это.</p></div><div className="grid gap-4 md:grid-cols-3"><Card><p className="text-slate-400">Средний балл</p><b className="text-4xl">{averageGrade(grades)}</b><p className="text-xs text-slate-500">Источник: {grades.length} оценок из табеля</p></Card><Card><p className="text-slate-400">Сила базы знаний</p><b className="text-4xl">{knowledgeCoverage(knowledge)}%</b><p className="text-xs text-slate-500">Средний memoryStrength по {knowledge.length} записям</p></Card><Card><p className="text-slate-400">Прогноз</p><b className="text-3xl">B1 ~ {months} мес.</b><p className="text-xs text-slate-500">Основано на активности, оценках и текущем темпе</p></Card></div><div className="grid gap-4 lg:grid-cols-2"><Card><h2 className="text-xl font-bold">Динамика оценок</h2><p className="text-sm text-slate-400">Это не случайный график: каждая точка — запись в табеле.</p><div className="h-72"><ResponsiveContainer><LineChart data={lineData}><CartesianGrid strokeDasharray="3 3" stroke="#1e293b"/><XAxis dataKey="n" stroke="#64748b"/><YAxis domain={[1,5]} stroke="#64748b"/><Tooltip contentStyle={{background:'#0f172a',border:'1px solid #334155',borderRadius:16}}/><Line dataKey="score" stroke="#67e8f9" strokeWidth={3}/></LineChart></ResponsiveContainer></div></Card><Card><h2 className="text-xl font-bold">Навыки</h2><p className="text-sm text-slate-400">“Словарь 5” значит не идеальный словарь вообще, а средний балл по заданиям словаря.</p><div className="h-72"><ResponsiveContainer><BarChart data={skillData}><CartesianGrid strokeDasharray="3 3" stroke="#1e293b"/><XAxis dataKey="skill" stroke="#64748b"/><YAxis domain={[1,5]} stroke="#64748b"/><Tooltip contentStyle={{background:'#0f172a',border:'1px solid #334155',borderRadius:16}} formatter={(v,n)=>[v,n==='score'?'AI score':'кол-во оценок']}/><Bar dataKey="score" fill="#8b5cf6" radius={[12,12,0,0]}/></BarChart></ResponsiveContainer></div></Card></div><div className="grid gap-4 md:grid-cols-2"><Card><h2 className="text-xl font-bold">Слабые темы</h2>{weakTopics(grades).map(w=><p key={w} className="text-red-200">• {w}</p>)}</Card><Card><h2 className="text-xl font-bold">Сильные темы</h2>{strongTopics(grades).map(w=><p key={w} className="text-emerald-200">• {w}</p>)}</Card></div></div>;
}
