import { CheckCircle2, Clock, HelpCircle } from 'lucide-react';
import { Card, Progress, Button } from '../components/ui';
import { useLearningStore } from '../store/useLearningStore';
import { averageGrade, currentStreak, knowledgeCoverage, recommendationProgress, weakTopics, weekActivity } from '../utils/analytics';
import { Area, AreaChart, ResponsiveContainer, Tooltip, XAxis } from 'recharts';

export default function Dashboard(){
 const {profile, grades, knowledge, recommendations, activity, toggleRecommendationStep, gradeRecommendation}=useLearningStore();
 const rec=recommendations[0]; const recProgress=rec?recommendationProgress(rec):0; const streak=currentStreak(activity); const weekly=weekActivity(activity);
 return <div className="space-y-5"><div><h1 className="text-3xl font-black">Dashboard</h1><p className="text-slate-400">Честная сводка: все цифры берутся из оценок, заданий, повторений и базы знаний.</p></div>
  <div className="grid gap-4 md:grid-cols-4"><Card><p className="text-slate-400">Средний балл</p><b className="text-4xl">{averageGrade(grades)}</b><p className="mt-2 text-xs text-slate-500">Источник: {grades.length} AI/учебных оценок</p></Card><Card><p className="text-slate-400">Learning Streak</p><b className="text-4xl">{streak.streak} дн.</b><p className="mt-2 text-xs text-slate-500">Rest days: {streak.restsLeft}/2. Считается по реальным learning actions.</p></Card><Card><p className="text-slate-400">Memory Strength</p><b className="text-4xl">{knowledgeCoverage(knowledge)}%</b><p className="mt-2 text-xs text-slate-500">Средняя сила памяти по базе знаний</p></Card><Card><p className="text-slate-400">Уровень</p><b className="text-4xl">{profile.level}</b><p className="mt-2 text-xs text-slate-500">Цель: {profile.targetLevel} / Ausbildung</p></Card></div>
  <div className="grid gap-4 lg:grid-cols-[1fr_420px]"><Card><div className="mb-4 flex items-center justify-between"><div><h2 className="text-xl font-bold">Активность недели</h2><p className="text-sm text-slate-400">Метрика: минуты обучения. Tooltip показывает источник данных.</p></div><span className="rounded-full bg-cyan-300/10 px-3 py-1 text-xs text-cyan-200">{activity.reduce((s,a)=>s+a.minutes,0)} мин всего</span></div><div className="h-64"><ResponsiveContainer><AreaChart data={weekly}><defs><linearGradient id="a" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#67e8f9" stopOpacity=".55"/><stop offset="100%" stopColor="#8b5cf6" stopOpacity=".05"/></linearGradient></defs><XAxis dataKey="day" stroke="#64748b"/><Tooltip contentStyle={{background:'#0f172a',border:'1px solid #334155',borderRadius:16}} formatter={(v,n)=>[`${v}`, n==='minutes'?'минуты':n]}/><Area type="monotone" dataKey="minutes" stroke="#67e8f9" fill="url(#a)" strokeWidth={3}/></AreaChart></ResponsiveContainer></div></Card>
  {rec && <Card><div className="flex items-start justify-between gap-3"><div><h2 className="text-xl font-bold">AI-рекомендация</h2><p className="mt-2 text-sm text-slate-400">Причина: {rec.reason}</p></div><span className="rounded-full bg-violet-400/15 px-3 py-1 text-sm text-violet-200">{recProgress}%</span></div><h3 className="mt-5 font-bold text-cyan-100">{rec.title}</h3><div className="mt-4 space-y-3">{rec.steps.map(s=><button key={s.id} onClick={()=>toggleRecommendationStep(rec.id,s.id)} className="flex w-full items-center gap-3 rounded-2xl bg-white/5 p-3 text-left hover:bg-white/10">{s.status==='done'?<CheckCircle2 className="text-emerald-300"/>:<Clock className="text-slate-500"/>}<span>{s.text}</span><span className="ml-auto text-xs text-slate-500">+{s.weight}%</span></button>)}</div><div className="mt-4"><Progress value={recProgress}/></div><div className="mt-4 flex flex-wrap gap-2"><span className="flex items-center gap-1 text-xs text-slate-500"><HelpCircle size={14}/> Оценка качества после выполнения:</span>{[1,2,3,4,5].map(v=><Button key={v} onClick={()=>gradeRecommendation(rec.id,v as 1|2|3|4|5)} className="px-3 py-1 text-sm">{v}</Button>)}</div></Card>}
  </div><Card><h2 className="text-xl font-bold">Что требует внимания</h2><div className="mt-3 flex flex-wrap gap-2">{weakTopics(grades).map(t=><span key={t} className="rounded-full bg-red-400/10 px-3 py-1 text-sm text-red-200">{t}</span>)}</div></Card></div>;
}
