import { Bot, CheckCircle2, Clock3 } from 'lucide-react';
import { Card, Button, Progress } from '../components/ui';
import { useLearningStore } from '../store/useLearningStore';
import { lessonProgress } from '../utils/analytics';

const statusMap = { planned:'запланировано', in_progress:'в работе', ai_review:'на AI-проверке', completed:'завершено', missed:'пропущено' } as const;
export default function Diary(){
 const {lessons, toggleLessonTask, requestAiReview, grades}=useLearningStore();
 return <div className="space-y-5"><div><h1 className="text-3xl font-black">Дневник</h1><p className="text-slate-400">Цифровой учебный журнал: задания проверяет AI, оценка остается по 5-бальной системе.</p></div>
 <Card><div className="mb-5 flex items-center justify-between"><div><h2 className="text-2xl font-bold">Учебная неделя</h2><p className="text-sm text-slate-400">Каждая строка — урок, домашка, статус AI-проверки и оценка.</p></div><span className="rounded-full bg-cyan-300/10 px-3 py-1 text-sm text-cyan-200">Неделя 22</span></div>
  <div className="overflow-x-auto"><table className="w-full min-w-[860px] border-separate border-spacing-y-3"><thead className="text-left text-sm text-slate-400"><tr><th className="px-4">Дата</th><th>Тема</th><th>Домашнее задание</th><th>AI статус</th><th>Оценка</th><th>Прогресс</th></tr></thead><tbody>{lessons.map(l=>{ const g=grades.find(x=>x.sourceLessonId===l.id); const p=lessonProgress(l); return <tr key={l.id} className="rounded-2xl bg-white/5"><td className="rounded-l-2xl px-4 py-4 font-semibold">{l.date}<br/><span className="text-xs text-slate-500">до {l.deadline.split(' ')[1]}</span></td><td className="py-4"><b>{l.title}</b><p className="text-sm text-slate-400">{l.topics.join(' · ')}</p></td><td className="max-w-md py-4 text-sm text-slate-300">{l.homework}</td><td className="py-4"><span className="rounded-full bg-slate-700/70 px-3 py-1 text-sm">{statusMap[l.status]}</span></td><td className="py-4 text-xl font-black text-cyan-200">{g?.score || '—'}</td><td className="rounded-r-2xl py-4 pr-4"><div className="min-w-36"><Progress value={p}/><span className="text-xs text-slate-500">{p}%</span></div></td></tr>})}</tbody></table></div>
 </Card>
 <div className="grid gap-4 lg:grid-cols-3">{lessons.map(l=><Card key={l.id} className="space-y-4"><div className="flex items-start justify-between gap-3"><div><p className="text-sm text-cyan-200">{l.date}</p><h3 className="text-xl font-bold">{l.title}</h3></div><span className="rounded-full bg-white/10 px-3 py-1 text-sm">{statusMap[l.status]}</span></div><p className="text-sm text-slate-400">{l.homework}</p><div className="space-y-2">{l.tasks.map(t=><button key={t.id} onClick={()=>toggleLessonTask(l.id,t.id)} className="flex w-full items-center gap-3 rounded-2xl bg-white/5 p-3 text-left hover:bg-white/10">{t.status==='done'?<CheckCircle2 className="text-emerald-300"/>:<Clock3 className="text-slate-500"/>}<span className="text-sm">{t.text}</span><span className="ml-auto text-xs text-slate-500">{t.weight}%</span></button>)}</div><Progress value={lessonProgress(l)}/><Button onClick={()=>requestAiReview(l.id)} className="w-full"><Bot className="mr-2 inline" size={18}/> Отправить на AI-проверку</Button>{l.aiFeedback&&<p className="rounded-2xl bg-cyan-300/10 p-3 text-sm text-cyan-100">{l.aiFeedback}</p>}</Card>)}</div></div>;
}
