import { CheckCircle2, Lock, Target } from 'lucide-react';
import { Card, Progress } from '../components/ui';
import { roadmap } from '../data/mockData';
import { useLearningStore } from '../store/useLearningStore';
import { roadmapProgress } from '../utils/analytics';

const statusText = { locked:'закрыто', active:'активно', needs_review:'повторить', completed:'закрыто AI' } as const;
export default function Roadmap(){
 const grades=useLearningStore(s=>s.grades); const progress=roadmapProgress(roadmap); const next=roadmap.flatMap(r=>r.topics).find(t=>t.status==='active'||t.status==='needs_review');
 return <div className="space-y-5"><div><h1 className="text-3xl font-black">Roadmap обучения</h1><p className="text-slate-400">Теперь это не декоративные проценты, а карта навыков: тема закрывается только после AI-проверки и оценки минимум 4/5.</p></div><Card><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm text-cyan-200">Главный прогресс</p><h2 className="text-3xl font-black">{progress}% verified path</h2><p className="text-sm text-slate-400">Основано на статусах тем, а не на случайной цифре.</p></div>{next&&<div className="rounded-3xl bg-cyan-300/10 p-4"><p className="text-sm text-slate-400">Следующая цель</p><b>{next.title}</b><p className="text-sm text-cyan-200">Нужно получить {next.requiredScore}/5</p></div>}</div><div className="mt-4"><Progress value={progress}/></div></Card><div className="grid gap-4">{roadmap.map(level=><Card key={level.level}><div className="mb-5 flex items-start justify-between"><div><p className="text-sm text-cyan-200">{level.level}</p><h2 className="text-2xl font-black">{level.title}</h2><p className="text-slate-400">{level.objective}</p></div><Target className="text-cyan-200"/></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{level.topics.map(t=><div key={t.id} className="rounded-3xl border border-white/10 bg-white/5 p-5"><div className="mb-3 flex items-center justify-between"><span className="rounded-full bg-white/10 px-3 py-1 text-xs">{statusText[t.status]}</span>{t.status==='locked'?<Lock size={18} className="text-slate-500"/>:<CheckCircle2 size={18} className={t.status==='completed'?'text-emerald-300':'text-cyan-300'}/>}</div><h3 className="font-bold">{t.title}</h3><p className="mt-2 text-sm text-slate-400">{t.description}</p><p className="mt-3 text-sm">Оценка: <b className="text-cyan-200">{t.currentScore || '—'}</b> / нужно {t.requiredScore}</p><div className="mt-4 space-y-3">{t.skills.map(s=><div key={s.name}><div className="mb-1 flex justify-between text-xs text-slate-500"><span>{s.name}</span><span>{s.progress}%</span></div><Progress value={s.progress}/></div>)}</div></div>)}</div></Card>)}</div><Card><h2 className="text-xl font-bold">Как Roadmap связан с системой</h2><p className="mt-2 text-slate-400">Задания из дневника создают оценки. Оценки влияют на статус тем. Слабые темы уходят в AI-рекомендации и повторения базы знаний. Поэтому roadmap отвечает на вопрос “что делать дальше”, а не просто показывает красивые проценты.</p></Card></div>;
}
