import { useRef, useState } from 'react';
import { Download, Upload } from 'lucide-react';
import { Button, Card, Select } from '../components/ui';
import { useLearningStore } from '../store/useLearningStore';

export default function Settings(){
 const {theme,setTheme,language,setLanguage,themeSettings,setThemeSettings,exportData,importData}=useLearningStore(); const fileRef=useRef<HTMLInputElement>(null); const [msg,setMsg]=useState('');
 const backup=()=>{ const blob=new Blob([exportData()],{type:'application/json'}); const url=URL.createObjectURL(blob); const a=document.createElement('a'); a.href=url; a.download=`deutsch-learning-backup-${new Date().toISOString().slice(0,10)}.json`; a.click(); URL.revokeObjectURL(url); };
 const restore=(file?:File)=>{ if(!file) return; const r=new FileReader(); r.onload=()=>{ const res=importData(String(r.result)); setMsg(res.ok?'Backup восстановлен':'Ошибка: '+res.error); }; r.readAsText(file); };
 return <div className="space-y-5"><div><h1 className="text-3xl font-black">Настройки</h1><p className="text-slate-400">Настройки должны реально менять систему: язык интерфейса, тему, плотность и резервные копии.</p></div><div className="grid gap-4 lg:grid-cols-2"><Card><h2 className="text-xl font-bold">Интерфейс</h2><div className="mt-4 grid gap-4"><label><span className="mb-2 block text-sm text-slate-400">Тема</span><Select value={theme} onChange={e=>setTheme(e.target.value as 'dark'|'light')}><option value="dark">Dark</option><option value="light">Light</option></Select></label><label><span className="mb-2 block text-sm text-slate-400">Язык интерфейса</span><Select value={language} onChange={e=>setLanguage(e.target.value as 'ru'|'de')}><option value="ru">Русский</option><option value="de">Deutsch</option></Select><p className="mt-2 text-xs text-slate-500">Перевод учебного контента не меняется — меняется только интерфейс. Полная i18n-система подготовлена как следующий слой.</p></label><label><span className="mb-2 block text-sm text-slate-400">Accent color</span><Select value={themeSettings.accent} onChange={e=>setThemeSettings({accent:e.target.value as any})}><option value="cyan">Cyber Cyan</option><option value="violet">Violet</option><option value="emerald">Emerald</option><option value="amber">Amber</option><option value="rose">Rose</option></Select></label><label><span className="mb-2 block text-sm text-slate-400">Плотность интерфейса</span><Select value={themeSettings.density} onChange={e=>setThemeSettings({density:e.target.value as any})}><option value="comfortable">Comfortable</option><option value="compact">Compact</option></Select></label></div></Card><Card><h2 className="text-xl font-bold">Backup & Restore</h2><p className="mt-2 text-slate-400">Это нужно, чтобы не потерять прогресс: оценки, базу знаний, дневник, AI-историю и настройки.</p><div className="mt-5 grid gap-3"><Button onClick={backup} className="w-full py-4"><Download className="mr-2 inline"/>Скачать backup</Button><input ref={fileRef} type="file" accept="application/json" className="hidden" onChange={e=>restore(e.target.files?.[0])}/><Button onClick={()=>fileRef.current?.click()} className="w-full bg-slate-700 py-4 text-white hover:bg-slate-600"><Upload className="mr-2 inline"/>Восстановить из файла</Button>{msg&&<p className="rounded-2xl bg-white/5 p-3 text-sm text-cyan-100">{msg}</p>}<div className="rounded-3xl bg-white/5 p-4 text-sm text-slate-400"><b className="text-white">Что входит:</b><p>✓ База знаний<br/>✓ Оценки и табель<br/>✓ Дневник и задания<br/>✓ AI история<br/>✓ Настройки</p></div></div></Card></div><Card><h2 className="text-xl font-bold">Почему нет “сбросить прогресс”?</h2><p className="mt-2 text-slate-400">Сброс прогресса ломает идею дневника и аналитику. Вместо этого используются backup, архивирование и новая учебная фаза. Так история обучения остается честной.</p></Card></div>;
}
